sonar.projectKey=zero-trust-supply-chain

sonar.projectName=Zero Trust Supply Chain

sonar.sources=app

sonar.python.version=3.11

sonar.sourceEncoding=UTF-8

sonar.python.coverage.reportPaths=coverage.xml