apiVersion: v1
kind: Pod

metadata:
  name: no-resources

spec:
  # securityContext:
  #   readOnlyRootFilesystem: true // false or missing will be blocked
  containers:
    - name: nginx
      image: nginx:1.27
